version: '3.8'

services:
  web1:
    build: ./web
    ports:
      - "3001:3000"
    volumes:
      - ./web/prisma/dev.db:/usr/src/app/prisma/dev.db

  web2:
    build: ./web
    ports:
      - "3002:3000"
    volumes:
      - ./web/prisma/dev.db:/usr/src/app/prisma/dev.db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - web1
      - web2