services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  auth-leader:
    build: ./auth
    ports:
      - '8100:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
        yarn prisma migrate deploy &&
        npm start"

  auth-1:
    build: ./auth
    ports:
      - '8101:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npm start"

  auth-2:
    build: ./auth
    ports:
      - '8102:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npm start"

  article-leader:
    build: ./article
    ports:
      - '8200:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
        yarn prisma migrate deploy &&
        npm start"

  article-1:
    build: ./article
    ports:
      - '8201:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npm start"

  article-2:
    build: ./article
    ports:
      - '8202:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npm start"

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: "npm start"

  caddy:
    image: caddy:latest
    ports:
      - '80:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - auth-leader
      - article-leader

volumes:
  db-data: