services:
  caddy:
    image: caddy:latest
    ports:
      - '80:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

  app:
    build: ./app
    ports:
      - '3000:3000'
      