# - name: "Configure AWS Credentials" Action for GitHub Actions
# uses: aws-actions/configure-aws-credentials@v4.0.2
name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sync-s3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::361769566809:role/skkuding-study-oidc
          aws-region: ap-northeast-2

      - name: Upload file to S3
        run: |
          aws s3 cp "8. GitHub Actions/static/index.html" s3://skkuding-study/index.html
          aws s3 cp "8. GitHub Actions/static/script.js" s3://skkuding-study/script.js
          aws s3 cp "8. GitHub Actions/static/style.css" s3://skkuding-study/style.css

  update-ecs:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::361769566809:role/skkuding-study-oidc
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: 361769566809.dkr.ecr.ap-northeast-2.amazonaws.com/skkuding-study
          REPOSITORY: skkuding-study
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG "./8. GitHub Actions/Dockerfile"
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
