name: "CodeQL"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read

    container:
      image: mcr.microsoft.com/cstsectools/codeql-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Build
        run: |
          cd ./4. EC2
          sudo npm install
          sudo npm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

